### ISSUE TITLE
AdapterError: Connection is already registered

### ISSUE THREAD

**Issue by bjones2013** [balderdashy/sails-mongo#225]
I am getting the following stack trace when attempting to run tests (starting with the second test spec)

    AdapterError: Connection is already registered
      at Object.module.exports.adapter.registerConnection (/Users/brandonjones/work/cabtrax/cabtraxV2/server/node_modules/sails-mongo/lib/adapter.js:81:60)
      at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:202:29
      at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:125:13
      at Array.forEach (native)
      at _each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:46:24)
      at Object.async.each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:124:9)
      at Array.async.auto.registerConnections [as 1] (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline.js:175:13)
      at /usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:487:38
      at Array.forEach (native)
      at _each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:46:24)

To make sure it wasn't something I just screwed up I tested with both local disk and in memory adapters. I couldn't reproduce the issue with either. 

In the before and after hook I use a modified version of the appHelper.js (location at https://gist.github.com/logan-pugh/abd9bed7b97870d10560#file-apphelper-js)

A sample spec for me is as follows : 

```javascript
var appHelper = require('../helpers/appHelper'),
    expect = require('chai').expect,
    sinon = require('sinon');


//note data validation is part of the framework so its testing will be minimal
describe('User model', function(){

  var user;
  // Global before hook
  before(function(done) {
    appHelper.lift(done);
  });

  // Global after hook
  after(function(done) {
    User.destroy({})
    .exec(function(err){
      appHelper.lower(done);
    });
  });
```
... 

Any ideas?

**Comment by bjones2013** [comment]
Wow just solved it so I suppose close this for now. After I already posted my request I thought about reinstalling mong-sails in case there were updates. Anyway the reinstall fixed it.
