### ISSUE TITLE
MongoError: topology was destroyed

### ISSUE THREAD

**Issue by vincurekf** [balderdashy/sails-mongo#266]
Hi guys,
I really don't know what to do with this,
I have latest version of sailsjs, mongo and sails-mongo installed,
clean project and just want to ../create, but this error keeps popping out in console.
Does anyone know what to do?
```
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: topology was destroyed
    at Server.insert (/var/sails-apps/smokers/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:797:49)
    at Server.insert (/var/sails-apps/smokers/node_modules/sails-mongo/node_modules/mongodb/lib/server.js:311:17)
    at insertDocuments (/var/sails-apps/smokers/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:493:19)
    at Collection.insert (/var/sails-apps/smokers/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:535:10)
    at Collection.insert (/var/sails-apps/smokers/node_modules/sails-mongo/lib/collection.js:182:48)
    at Object.module.exports.adapter.create (/var/sails-apps/smokers/node_modules/sails-mongo/lib/adapter.js:273:18)
    at module.exports.create (/var/sails-apps/smokers/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:85:13)
    at bound.createValues (/var/sails-apps/smokers/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:213:16)
    at /var/sails-apps/smokers/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:74:20
    at /var/sails-apps/smokers/node_modules/sails/node_modules/async/lib/async.js:254:17
    at /var/sails-apps/smokers/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /var/sails-apps/smokers/node_modules/sails/node_modules/async/lib/async.js:251:21
    at /var/sails-apps/smokers/node_modules/sails/node_modules/async/lib/async.js:615:34
    at /var/sails-apps/smokers/node_modules/sails/node_modules/async/lib/async.js:157:25
    at bound.<anonymous> (/var/sails-apps/smokers/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn (/var/sails-apps/smokers/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:41:10)

Details:  MongoError: topology was destroyed
```

I have absolutely no idea what went wrong there.
I have other project running on the same server and sails-mongo is working properly there, no errors, can create, update, destroy...

**Comment by vincurekf** [comment]
[Anandapriyan S.D](http://stackoverflow.com/a/29969547/1798395) found solution.

**Comment by rcholic** [comment]
re-installing the 0.10.6 works only for the first CRUD operation, after which it shows the same error again: topology was destroyed

**Comment by dmarcelino** [comment]
Yeap, that was caused by #260. @andypham, is there any workaround for this or Mongo <=2.4 users will have to stick with sails-mongo `0.10.6`?

**Comment by particlebanana** [comment]
If needed we can revert it and push out the mongo driver update to `0.11.0` I guess. Didn't realize it would break on certain versions of mongo.

**Comment by dmarcelino** [comment]
@particlebanana, me neither. I think we should do that, revert PR #260 and create a new `0.11` branch for those changes.

**Comment by andypham** [comment]
@particlebanana I think user of mongo version <=2.4 should stick with sails mongo 0.10.6. We should publish version 0.11.0 for updating the mongo driver 2.0 change as it allow us to move forward. We should publish a release note so the users are aware of this. Mongo native 2.0 has breaking API changes.

**Comment by dmarcelino** [comment]
We shouldn't be making breaking changes on patch releases as people doing `npm update` will get a nasty surprise. I think we'll need to revert the changes, [deprecate](https://docs.npmjs.com/cli/deprecate) 0.10.7 and release 0.10.8.

**Comment by tjwebb** [comment]
If we upgraded the mongo driver, this should never have been published in the same minor version series. 

> I think we'll need to revert the changes, deprecate 0.10.7 and release 0.10.8.

Yes, and release the new mongo driver in 0.11

**Comment by andypham** [comment]
@dmarcelino @tjwebb Agreed.

**Comment by particlebanana** [comment]
I'm making a new branch for `0.10.x` with the reverted merge and will unpublish `0.10.7`. This way we can push hot fixes to `0.10.x` and master will become `0.11`.

**Comment by andypham** [comment]
@particlebanana +1

**Comment by dmarcelino** [comment]
Sounds good @particlebanana, go for it!

**Comment by particlebanana** [comment]
Ok done, we have `0.11.0` and `0.10.8` published. We need to add a note on the README of which version to use.

**Comment by andypham** [comment]
@particlebanana Thanks. I will add it to the README and create a Release note.

**Comment by golojads** [comment]
Hi,
Updated to latest version but problem still exists. My setup:
sails-mongo  ```0.11.0```
Sails.js  ```0.11.0```
Mongodb ```3.0.2```
OSX Yosemite ```10.10.3```
Node.js ```0.10.28```

Is there anything else I forgot to update ?
Thank you.

**Comment by andypham** [comment]
@golojads Can you post your error?

**Comment by golojads** [comment]
@andypham, here is error:
```
debug: Port        : 1337
debug: --------------------------------------------------------
debug: Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: topology was destroyed
    at Server.insert (/Users/jg/work/angels/back-office-api/sails/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:797:49)
    at Server.insert (/Users/jg/work/angels/back-office-api/sails/node_modules/sails-mongo/node_modules/mongodb/lib/server.js:311:17)
    at insertDocuments (/Users/jg/work/angels/back-office-api/sails/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:493:19)
    at Collection.insert (/Users/jg/work/angels/back-office-api/sails/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:535:10)
    at Collection.insert (/Users/jg/work/angels/back-office-api/sails/node_modules/sails-mongo/lib/collection.js:182:48)
    at Object.module.exports.adapter.create (/Users/jg/work/angels/back-office-api/sails/node_modules/sails-mongo/lib/adapter.js:273:18)
    at module.exports.create (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:85:13)
    at bound.createValues (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:213:16)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:74:20
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:615:34
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:157:25
    at bound.<anonymous> (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:41:10)
```

**Comment by RasCarlito** [comment]
Hi !

Same problem for me =(
My setup is the same as @golojads except my OS is Ubuntu 14.04

```
error: Sending 500 ("Server Error") response: 
 Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: topology was destroyed
    at Server.insert (/home/carlogren/www/unow/chatter/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:797:49)
    at Server.insert (/home/carlogren/www/unow/chatter/node_modules/sails-mongo/node_modules/mongodb/lib/server.js:311:17)
    at insertDocuments (/home/carlogren/www/unow/chatter/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:493:19)
    at Collection.insert (/home/carlogren/www/unow/chatter/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:535:10)
    at Collection.insert (/home/carlogren/www/unow/chatter/node_modules/sails-mongo/lib/collection.js:182:48)
    at Object.module.exports.adapter.create (/home/carlogren/www/unow/chatter/node_modules/sails-mongo/lib/adapter.js:273:18)
    at module.exports.create (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:85:13)
    at bound.createValues (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:213:16)
    at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:74:20
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:615:34
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:157:25
    at null.<anonymous> (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:41:10)

Details:  MongoError: topology was destroyed
```

**Comment by RasCarlito** [comment]
Is installed sails-mongo 0.10.8 instead of 0.11.0 and the error is gone =)

**Comment by Wicked0ne** [comment]
@RasCarlito Thanks! I was also getting this same error. Reverting to 0.10.8 seems to have solved it

**Comment by andypham** [comment]
So I was able to reproduce the above error in sails-mongo integration tests. See the this gist.
https://gist.github.com/andypham/799291b7f691a92af9d5
I have not yet figure out the root cause, but would like to share with you guys.

**Comment by particlebanana** [comment]
So the issue here seems to be the connection is closed? I'm not sure what I'm looking at in @andypham's gist. Is adding the setTimeout causing the issue?

**Comment by limitmaker** [comment]
Same issue.  Went to 0.10.8 and now works just fine.

**Comment by andypham** [comment]
@particlebanana In the gist the setTimeout is being used as a way to simulate a socket timeout after the socket has been opened.

**Comment by particlebanana** [comment]
Just published `0.11.1` which *should* fix this. Can you guys give it a test spin.

**Comment by limitmaker** [comment]
Working here!

**Comment by golojads** [comment]
fixed, thanks

**Comment by devinivy** [comment]
Calling it closed then!  If there are any more issues, we can reopen.

**Comment by siliconprime-longle** [comment]
I'm on `0.11.1` and still see the error. I called multiple insert to DB, it only works for first 3 insert calls.
My packages version:
sails: `0.11.0`,
mongodb: `2.6.5`,
sails-mongo: `0.11.1`

Error:
```
[working_dir]/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: topology was destroyed
    at Server.insert ([working_dir]/node_modules/sails-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:894:49)
    at Server.insert ([working_dir]/node_modules/sails-mongo/node_modules/mongodb/lib/server.js:311:17)
    at insertDocuments ([working_dir]/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:493:19)
    at Collection.insert ([working_dir]/node_modules/sails-mongo/node_modules/mongodb/lib/collection.js:535:10)
    at Collection.insert ([working_dir]/node_modules/sails-mongo/lib/collection.js:182:48)
    at Object.module.exports.adapter.create ([working_dir]/node_modules/sails-mongo/lib/adapter.js:274:18)
    at module.exports.create ([working_dir]/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:85:13)
    at bound.createValues ([working_dir]/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:213:16)
    at [working_dir]/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/create.js:74:20
    at [working_dir]/node_modules/async/lib/async.js:254:17
    at [working_dir]/node_modules/async/lib/async.js:157:25
    at [working_dir]/node_modules/async/lib/async.js:251:21
    at [working_dir]/node_modules/async/lib/async.js:615:34
    at [working_dir]/node_modules/async/lib/async.js:157:25
    at bound.<anonymous> ([working_dir]/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn ([working_dir]/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:41:10)
            
```

**Comment by devinivy** [comment]
I think we should enforce defaults listed here: http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html

Can someone trying to set the server `socketOptions.socketTimeoutMS` to the default `0`.  That should keep the socket open forever, which is what I think we're trying to achieve.  Shouldn't the adapter default to the mongo driver's defaults?

**Comment by devinivy** [comment]
See #277 for a proposed fix.

**Comment by StoloADiane** [comment]
Sorry to bother you guys, but I still I have this issue, using Sails 0.11.1

**Comment by devinivy** [comment]
The most recent version is not yet published.  In the meantime, you can fix this by adjusting your connection config options: https://github.com/balderdashy/sails-mongo/pull/277#issuecomment-101293810
>```js
devMongodbServer: { // connection name
    port: 27017,
    database: 'dev-mongodb-server',
    poolSize: 5,
    socketOptions: {
        noDelay: true,
        connectTimeoutMS: 0,
        socketTimeoutMS: 0
    }
}
```

**Comment by StoloADiane** [comment]
Thank you very much @devinivy  ! :)
