### ISSUE TITLE
TypeError: Object #<bound> has no method 'query'

### ISSUE THREAD

**Issue by moonstruck** [balderdashy/sails-mongo#296]
After installing https://github.com/GladysProject/Gladys when I run the program I'm getting error from sails-mongo.

My settings:

      glnv: {
        adapter: 'sails-mongo',
        host: 'localhost',
        port: 27017,
        user: 'blah',
        password: 'blah',
        database: 'blah'
      },

Running node app.js creates all collections from models.

Error Message/Logs:

    node app.js 
    info: User hook policies loaded from /home/vagrant/glnv/api/hooks/example/policies.
    info: User hook config loaded from /home/vagrant/glnv/api/hooks/example/config.
    info: User hook models loaded from /home/vagrant/glnv/api/hooks/example/lib/../models.
    info: User hook services loaded from /home/vagrant/glnv/api/hooks/example/lib/../services.
    info: User hook controllers loaded from /home/vagrant/glnv/api/hooks/example/lib/../models.
    info: 
    info:                .-..-.
    info: 
    info:    Sails              <|    .-..-.
    info:    v0.11.0             |\
    info:                       /|.\
    info:                      / || \
    info:                    ,'  |'  \
    info:                 .-'.-==|/_--'
    info:                 `--'-------' 
    info:    __---___--___---___--___---___--___
    info:  ____---___--___---___--___---___--___-__
    info: 
    info: Server lifted in `/home/vagrant/glnv`
    info: To see your app, visit http://localhost:1337
    info: To shut down Sails, press <CTRL> + C at any time.
    debug: --------------------------------------------------------

    /home/vagrant/glnv/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:97
        process.nextTick(function() { throw err; });
                                            ^
    TypeError: Object #<bound> has no method 'query'
        at Object.module.exports.scheduleAllAlarms (/home/vagrant/glnv/api/services/AlarmService.js:134:9)
        at Object.bound [as scheduleAllAlarms] (/home/vagrant/glnv/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
        at Object.module.exports.onStart (/home/vagrant/glnv/api/services/StartService.js:29:16)
        at Object.bound [as onStart] (/home/vagrant/glnv/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
        at /home/vagrant/glnv/config/bootstrap.js:19:18
        at wrapper (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
        at applyInOriginalCtx (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
        at wrappedCallback (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
        at _normalizeCallback.callback.success (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/switchback/li
    b/normalize.js:33:31)
        at _switch (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
        at /home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/destroy.js:123:11
        at /home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:189:25
        at bound.<anonymous> (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
        at fn (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:136:10)
        at iterate (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:181:13)
        at Object.async.eachSeries (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:197:9)

Any insights about this error will be helpful.

**Comment by moonstruck** [comment]
This is actually not sails-mongo issue. The issue is Gladys requires RDBMS. Their config examples was misleading.
