### ISSUE TITLE
Many to Many Errors on populate

### ISSUE THREAD

**Issue by ajp76054** [balderdashy/sails-mongo#328]
I have two models User & Group

User - 
```
module.exports = {
  identity: 'user',
  attributes: {
  	firstName: {
  		type: 'string',
  		required: true
  	},
  	lastName: {
  		type: 'string',
  		required: true
  	},
  	userName: {
  		type: 'string',
  		required: true,
  		unique: true
  	},
  	email: {
  		type: 'string',
  		required: true,
  		unique: true
  	},
  	phones: {
  		type: 'array',
  		required: false
  	},
  	userType: {
  		type: 'integer',
  		defaultsTo: 0,
  	},
  	password: {
  		type: 'string'
  	},
  	passwordUpdated: {
  		type: 'date',
  		defaultsTo: new Date()
  	},
  	status: {
  		type: 'string',
  		defaultsTo: 'registered'
  	},
  	active: {
  		type: 'boolean',
  		defaultsTo: true
  	},
  	isOnline: {
  		type: 'boolean',
  		defaultsTo: false
  	},
        groupName: {
  		model: 'group'
  	}
}
};
```
Group - 
```
module.exports = {
  identity: 'group',
  attributes: {
  	name: {
  		type: 'string',
  	},
  	users: {
  		collectoin: 'user',
  		via: 'groupName'
  	}
  }
};
```

Currently there are two users and one group and when I run the sails console and execute the following code I get this error:

```
group.find().populate('users').exec(console.log)
Error: Encountered unexpected error while building join instructions for `.populate("users")`
Details:
[TypeError: Cannot read property 'attributes' of undefined]
    at Deferred.populate (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/deferred.js:279:11)
    at repl:1:14
    at REPLServer.defaultEval (repl.js:134:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:129:20)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
    at ReadStream.emit (events.js:110:17)
    at readline.js:1175:14
    at Array.forEach (native)
    at emitKeys (readline.js:993:10)
    at ReadStream.onData (readline.js:910:14)
```

Not sure if I am just using this wrong or what the deal is?

**Comment by ajp76054** [comment]
Did more digging and noticed I had a one to many.  My apologize for this.

**Comment by devinivy** [comment]
No worries!  Thanks for letting us know.
