### ISSUE TITLE
E11000 Kills server

### ISSUE THREAD

**Issue by Mordred** [balderdashy/sails-mongo#336]
You are not testing if the match is successfull: https://github.com/balderdashy/sails-mongo/blob/master/lib/utils.js#L183

```
TypeError: Cannot read property '1' of null
    at Object.clarifyError (/Users/martin/projects/freya/artfilm/intranet/node_modules/sails-mongo/lib/utils.js:184:26)
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/sails-mongo/lib/adapter.js:280:33
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/sails-mongo/lib/collection.js:178:20
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/lib/collection.js:448:20
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/lib/collection.js:547:14
    at resultHandler (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/lib/bulk/ordered.js:412:14)
    at /Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:756:13
    at [object Object].Callbacks.emit (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/martin/projects/freya/artfilm/intranet/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

I think that the regexp is invalid, because message is not starting with E11000:
```
insertDocument :: caused by :: 11000 E11000 duplicate key error index: app.user.$email_1  dup key: { : "somebody@example.com" }
```

**Comment by gayanhewa** [comment]
Looks like this was broken in the latest release , the regex broke the issue. For now I am testing  a patch for in the util.js which is causing the issue when the regex doesn't result in a match. Not ready for a pull request yet. But you can use it to patch locally until something is released.

```
exports.clarifyError = function clarifyError(err) {

  // MongoDB duplicate key error code
  if(err.code !== 11000) {
    return err;
  }

  // Example errmsg: `E11000 duplicate key error index: db_name.model_name.$attribute_name_1 dup key: { : "value" }`
  //  var matches = /^E11000 duplicate key error index: .*?\..*?\.\$(.*?)_\d+ dup key: { : (.*) }$/.exec(err.errmsg);
  var matcher = 'insertDocument :: caused by :: 11000 E11000 duplicate key error index: \(.*)\  dup key: { : "\(.*)\" }'
  var matches = err.errmsg.match(matcher);

  var fieldName = matches[1]; // name of index (without _[digits] at the end)
  var value;
  try {
    value = JSON.parse(matches[2]); // attempt to convert the value to a primitive representation
  } catch (x) {
    value = matches[2]; // for non-serializable objects (e.g. ObjectId representations), return as-is
  }

  var validationError = {
    code: 'E_UNIQUE',
    invalidAttributes: {},
    originalError: err
  };

  validationError.invalidAttributes[fieldName] = [
    {
      rule: 'unique',
      value: value
    }
  ];

  return validationError;
};
```

**Comment by gayanhewa** [comment]
@mmiller42 can you verify this on the recent pull request ?

**Comment by Mordred** [comment]
See #337

**Comment by devinivy** [comment]
Bummer– sorry about that!  We'll get #337 through as soon as we can.
