### ISSUE TITLE
when run node app.js sails-mongo "TypeError: Cannot read property 'close' of undefined"

### ISSUE THREAD

**Issue by xchl** [balderdashy/sails-mongo#352]
use mogodb 3.0.6
details info:    

```
at /www/12xue-mall-server/node_modules/sails-mongo/lib/adapter.js:138:13
    at /www/12xue-mall-server/node_modules/sails-mongo/node_modules/async/lib/async.js:187:20
    at /www/12xue-mall-server/node_modules/sails-mongo/node_modules/async/lib/async.js:239:13
    at _arrayEach (/www/12xue-mall-server/node_modules/sails-mongo/node_modules/async/lib/async.js:91:13)
    at _each (/www/12xue-mall-server/node_modules/sails-mongo/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/www/12xue-mall-server/node_modules/sails-mongo/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/www/12xue-mall-server/node_modules/sails-mongo/node_modules/async/lib/async.js:215:22)
    at Object.module.exports.adapter.teardown (/www/12xue-mall-server/node_modules/sails-mongo/lib/adapter.js:137:22)
    at /www/12xue-mall-server/node_modules/sails/lib/hooks/orm/index.js:244:19
    at /www/12xue-mall-server/node_modules/sails/node_modules/async/lib/async.js:122:13
    at _each (/www/12xue-mall-server/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/www/12xue-mall-server/node_modules/sails/node_modules/async/lib/async.js:121:9)
    at Sails.hook.teardown (/www/12xue-mall-server/node_modules/sails/lib/hooks/orm/index.js:241:13)
    at Sails.g (events.js:199:16)
    at Sails.emit (events.js:104:17)
    at Sails.emitter.emit (/www/12xue-mall-server/node_modules/sails/lib/app/private/after.js:50:1
```

**Comment by devinivy** [comment]
@xchl which version of sails-mongo are you using?  May be related to https://github.com/balderdashy/sails-mongo/pull/315– @jakutis mind taking a peek?

**Comment by jakutis** [comment]
@devinivy, you could merge https://github.com/balderdashy/sails-mongo/pull/353 or choose to fix this issue by just replacing

    return async.each(dbs, function (db, onClosed) {

with

    return async.each(_.compact(dbs), function (db, onClosed) {

**Comment by xchl** [comment]
@devinivy  I use "sails-mongo": "^0.11.4"

**Comment by devinivy** [comment]
Thanks all– we have two candidate fixes at #353 and #354 :)  It seems like one of them will be right, just need to decide.  The contributions are appreciated!

**Comment by elennaro** [comment]
I'm sorry, when will be release of the version with this patch?

**Comment by devinivy** [comment]
I'm hoping soon.  @particlebanana any thoughts?

**Comment by randallmeeker** [comment]
please!

**Comment by mstroeck** [comment]
:+1:

**Comment by particlebanana** [comment]
Published sails-mongo `0.11.5`

**Comment by jaumard** [comment]
Just have this error and sails-mongo 0.11.5 doesn't fix the problem :(  What can I do ? 
```
/var/www/lisa/node_modules/sails-mongo/lib/adapter.js:138
          db.close(onClosed);
            ^

TypeError: Cannot read property 'close' of undefined
    at /var/www/lisa/node_modules/sails-mongo/lib/adapter.js:138:13
    at /var/www/lisa/node_modules/sails-mongo/node_modules/async/lib/async.js:187:20
    at /var/www/lisa/node_modules/sails-mongo/node_modules/async/lib/async.js:239:13
    at _arrayEach (/var/www/lisa/node_modules/sails-mongo/node_modules/async/lib/async.js:91:13)
    at _each (/var/www/lisa/node_modules/sails-mongo/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/var/www/lisa/node_modules/sails-mongo/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/var/www/lisa/node_modules/sails-mongo/node_modules/async/lib/async.js:215:22)
    at Object.module.exports.adapter.teardown (/var/www/lisa/node_modules/sails-mongo/lib/adapter.js:137:22)
    at /var/www/lisa/node_modules/sails/lib/hooks/orm/index.js:244:19
    at /var/www/lisa/node_modules/sails/node_modules/async/lib/async.js:122:13
    at _each (/var/www/lisa/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/var/www/lisa/node_modules/sails/node_modules/async/lib/async.js:121:9)
    at Sails.hook.teardown (/var/www/lisa/node_modules/sails/lib/hooks/orm/index.js:241:13)
    at Sails.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Sails.emit (events.js:166:7)
```

**Comment by mikehermes** [comment]
I have this problem in heroku but not on local. I tried forcing the latest on master. I'm lost.

**Comment by mikehermes** [comment]
Is there a way to debug/log the credentials heroku is using?

**Comment by dac2205** [comment]
I am having the same issue when connecting to MongoLab.

**Comment by dac2205** [comment]
I found the reason: default connection timeout is 20 seconds. db object not created will cause error.

**Comment by fabdrol** [comment]
any way fo fixing this @dac2205 ?

**Comment by sahildeliwala** [comment]
@fabdrol any way fo fixing this?
