### ISSUE TITLE
Not able to connect to remote mongo(compose.io)

### ISSUE THREAD

**Issue by ligerdave** [balderdashy/sails-mongo#358]
I am getting this. I have tried with different ways including telnet, mongo and a node code using native mongo driver which all connected successfully.

Using
"sails-mongo": "^0.11.4",
"sails": "~0.11.2",

| => sails lift

info: Starting app...

options.domain deprecated, use options.origin instead
error: A hook (`orm`) failed to load!
/Users/okay/workspace/project/node_modules/mongodb/lib/server.js:235
        process.nextTick(function() { throw err; })
                                            ^
TypeError: Cannot read property 'close' of undefined
    at /Users/okay/workspace/project/node_modules/sails-mongo/lib/adapter.js:138:13
    at /Users/okay/workspace/project/node_modules/sails-mongo/node_modules/async/lib/async.js:187:20
    at /Users/okay/workspace/project/node_modules/sails-mongo/node_modules/async/lib/async.js:239:13
    at _arrayEach (/Users/okay/workspace/project/node_modules/sails-mongo/node_modules/async/lib/async.js:91:13)
    at _each (/Users/okay/workspace/project/node_modules/sails-mongo/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/Users/okay/workspace/project/node_modules/sails-mongo/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/Users/okay/workspace/project/node_modules/sails-mongo/node_modules/async/lib/async.js:215:22)
    at Object.module.exports.adapter.teardown (/Users/okay/workspace/project/node_modules/sails-mongo/lib/adapter.js:137:22)
    at /Users/okay/workspace/project/node_modules/sails/lib/hooks/orm/index.js:244:19
    at /Users/okay/workspace/project/node_modules/sails/node_modules/async/lib/async.js:122:13
    at _each (/Users/okay/workspace/project/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/Users/okay/workspace/project/node_modules/sails/node_modules/async/lib/async.js:121:9)
    at Sails.hook.teardown (/Users/okay/workspace/project/node_modules/sails/lib/hooks/orm/index.js:241:13)
    at Sails.g (events.js:199:16)
    at Sails.emit (events.js:104:17)
    at Sails.emitter.emit (/Users/okay/workspace/project/node_modules/sails/lib/app/private/after.js:50:11)
    at /Users/okay/workspace/project/node_modules/sails/lib/app/lower.js:60:11
    at beforeShutdown (/Users/okay/workspace/project/node_modules/sails/lib/app/lower.js:35:12)
    at Sails.lower (/Users/okay/workspace/project/node_modules/sails/lib/app/lower.js:39:3)
    at Sails.bound (/Users/okay/workspace/project/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at sailsReady (/Users/okay/workspace/project/node_modules/sails/lib/app/lift.js:35:20)
    at /Users/okay/workspace/project/node_modules/sails/node_modules/async/lib/async.js:251:17

**Comment by ligerdave** [comment]
ok, the issue was that i had multiple connections in connections.js with same adapter. why is this still a bug? i thought it has been squared away

**Comment by devinivy** [comment]
You should be able to have multiple connections on the same adapter.  Perhaps there's another issue at hand causing you to experience https://github.com/balderdashy/sails-mongo/pull/353, which has been patched but not released.  Could you try using sails-mongo master branch?

**Comment by pdavid0** [comment]
+1 same issue here

**Comment by AleksandarFaraj** [comment]
**Quick ugly fix.**
To clarify what ligerdave said:
You may only have one connection using Sails-mongo or it will crash.

**Comment by mstroeck** [comment]
I also tried lots of things regarding this issue - having two or mongo connections definitely the culprit.

**Comment by devinivy** [comment]
@ligerdave is this resolved?  How did you fix it?

**Comment by AnvarPK** [comment]
i have same issue, how to solve it?

**Comment by fabier** [comment]
Ok, I have found a workaround in my case.
I had 3 connections using sails-mongo

**/config/connections.js**
```javascript
module.exports.connections = {
    mongodb: {
        adapter: 'sails-mongo',
        host: 'hoster.com',
        [...]
    },
    "mongodb-dev": {
        adapter: 'sails-mongo',
        host: 'localhost',
        [...]
    },
    "mongodb-test": {
        adapter: 'sails-mongo',
        host: 'localhost',
        [...]
    }
}
```
Since each one was for a specific environment, I injected each connection string into environment specific configuration file :

**/config/env/production.js**
```javascript
module.exports = {
    connections: {
        mongodb: {
            adapter: 'sails-mongo',
            host: 'hoster.com',
            [...]
        }
    }
}
````

**/config/env/test.js**
```javascript
module.exports = {
    connections: {
        "mongodb-test": {
            adapter: 'sails-mongo',
            host: 'localhost',
            [...]
        }
    }
}
````

**/config/env/development.js**
```javascript
module.exports = {
    connections: {
        "mongodb-dev": {
            adapter: 'sails-mongo',
            host: 'localhost',
            [...]
        }
    }
}
````

... **And I removed the ones in /config/connections.js**

And it works !!
