### ISSUE TITLE
Cannot read property 'close' of undefined - Multiple mongo dbs

### ISSUE THREAD

**Issue by manchuwook** [balderdashy/sails-mongo#373]
I cannot get my sails lifted.  I have two databases, one for sails and a second one for an app route.  I have made a second site, copied over api/config/views/tasks and .bowerrc/.sailsrc and run npm install/update - but I don't think it is my node_modules. I've also changed the package.json in mongodb-core to have the version of kerberos@~0.0.17.

I'm not sure what else to check here.

```
username@server:/srv/www/mywebsite2$ sails lift

info: Starting app...

warn: Sails' built-in layout support only works with the `ejs`, `handlebars`, `ractive` view engines.
warn: You're using `nunjucks`.
warn: Ignoring `sails.config.views.layout`...
error: A hook (`orm`) failed to load!
/srv/www/mywebsite2/node_modules/mongodb/lib/mongo_client.js:447
              throw err
                    ^
TypeError: Cannot read property 'close' of undefined
    at /srv/www/mywebsite2/node_modules/sails-mongo/lib/adapter.js:138:13
    at /srv/www/mywebsite2/node_modules/sails-mongo/node_modules/async/lib/async.js:187:20
    at /srv/www/mywebsite2/node_modules/sails-mongo/node_modules/async/lib/async.js:239:13
    at _arrayEach (/srv/www/mywebsite2/node_modules/sails-mongo/node_modules/async/lib/async.js:91:13)
    at _each (/srv/www/mywebsite2/node_modules/sails-mongo/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/srv/www/mywebsite2/node_modules/sails-mongo/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/srv/www/mywebsite2/node_modules/sails-mongo/node_modules/async/lib/async.js:215:22)
    at Object.module.exports.adapter.teardown (/srv/www/mywebsite2/node_modules/sails-mongo/lib/adapter.js:137:22)
    at /usr/local/lib/node_modules/sails/lib/hooks/orm/index.js:244:19
    at /usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:122:13
    at _each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/usr/local/lib/node_modules/sails/node_modules/async/lib/async.js:121:9)
    at Sails.hook.teardown (/usr/local/lib/node_modules/sails/lib/hooks/orm/index.js:241:13)
    at Sails.g (events.js:199:16)
    at Sails.emit (events.js:104:17)
    at Sails.emitter.emit (/usr/local/lib/node_modules/sails/lib/app/private/after.js:50:11)
```

**Comment by devinivy** [comment]
I think this was patched in https://github.com/balderdashy/sails-mongo/pull/353 / v0.11.5.  Can you try that out if you haven't already?

**Comment by manchuwook** [comment]
I do have sails-mongo@0.11.5

**Comment by dioptre** [comment]
+1

**Comment by ram-you** [comment]
It's really annoying that bug. Please fix it. Thank you.

**Comment by particlebanana** [comment]
Looking into it

**Comment by ram-you** [comment]
Hi @particlebanana .
Thank you very much. Your fixing solved the problem.

**Comment by particlebanana** [comment]
@manchuwook @dioptre @ram-you pushed out `0.11.6` which includes a patch.
