### ISSUE TITLE
Sails upgarde to 0.12 and sails-mongo 0.12 - Error when lowering sails

### ISSUE THREAD

**Issue by crobinson42** [balderdashy/sails-mongo#386]
I just started migrating my project to Sails 0.12 from 0.11. Everything works fine when running my app until I ctrl+c to lower in the terminal:

```
^Cverbose: Lowering sails...
verbose: Sent kill signal to child process (93338)...
verbose: Shutting down HTTP server...
/Users/coryrobinson/projects/therms/node_modules/sails-mongo/lib/adapter.js:348
      var collection = connectionObject.collections[collectionName];
                                       ^

TypeError: Cannot read property 'collections' of undefined
    at Object.module.exports.adapter.find (/Users/coryrobinson/projects/therms/node_modules/sails-mongo/lib/adapter.js:348:40)
    at module.exports.find (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:119:13)
    at _runOperation (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:411:29)
    at run (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:70:8)
    at module.exports.find (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:264:16)
    at wrapper [as find] (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at Deferred.exec (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/waterline/lib/waterline/query/deferred.js:485:16)
    at Object.module.exports.socketDisconnected (/Users/coryrobinson/projects/therms/api/controllers/OnlineController.js:80:5)
    at Object.wrapper [as socketDisconnected] (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at Object.module.exports.socketDisconnected (/Users/coryrobinson/projects/therms/api/services/SocketService.js:154:32)
    at Object.wrapper [as socketDisconnected] (/Users/coryrobinson/projects/therms/node_modules/sails/node_modules/lodash/index.js:3095:19)
    at /Users/coryrobinson/projects/therms/api/services/SocketService.js:114:14
    at /Users/coryrobinson/projects/therms/node_modules/sails/lib/hooks/session/index.js:30:16
    at Command.callback (/Users/coryrobinson/projects/therms/node_modules/connect-redis/lib/connect-redis.js:136:25)
    at RedisClient.return_reply (/Users/coryrobinson/projects/therms/node_modules/connect-redis/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/Users/coryrobinson/projects/therms/node_modules/connect-redis/node_modules/redis/index.js:332:14)
```

I'm using
- Node.js v4.3.1
- Sails v 0.12
Here's my package.json https://gist.github.com/crobinson42/4700facb3417e87025da

**Comment by crobinson42** [comment]
The issue was in my code base. I invoked `OnlineUsers.find(...)` on socket disconnect which was invoked when lowering the sails app.
